site_url: https://simallygames.github.io/swiftframework/
site_name: Swift Framework
theme:
  name: material

nav:
  - About: 'about.md'
  - Getting Started: 'gettingstarted.md'
  - Server:
    - General: 'server/server.md'